from HomeWorkProject import *

def main():
    print("Chapter 2")
    print("\n#1 convert():\n")
    convert()
    print("\n#3 convert2():\n")
    convert2()
    print("\n#9 km2miles():\n")
    km2miles()
    print("\n#11 calcullator():\n")
    calculator()
    print("\nChapter 3\n")
    print("\n#1 sphereAreaVolume():\n")
    sphereAreaVolume()
    print("\n#2 costOfPizza():\n")
    costOfPizza()
    print("\n#3 weight():\n")
    weight()
    print("\n#12 sumCube():\n")
    sumCube()
    print("\n#13 sumSeries():\n")
    sumSeries()
    print("\n#14 averageSeries():\n")
    averageSeries()
    print("\n#16 fibonacci():\n")
    fibonacci()
    print("\nChapter 4\n")
    print("\n#1  drawSquares():\n")
    drawSquares()  
    print("\n#2  archeryTarget():\n")
    archeryTarget()
    print("\n#3  face():\n")
    face()
    print("\n#4 winter():\n")
    winter()
    print("\n#7  intersection():\n")
    intersection()
    print("\n#10  triangleInfo():\n")
    triangleInfo()
    print("\n#11  fiveClickHome():\n")
    fiveClickHome()
    #currencyConverter() check pdf
    
main()

